import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="h-screen overflow-hidden">
            <body className="h-screen bg-black pb-3 relative overflow-hidden">
                {children}
            </body>
        </html>
    );
}
